/// Flutter icons MyPortfolio
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyPortfolio
///      fonts:
///       - asset: fonts/MyPortfolio.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyPortfolio {
  MyPortfolio._();

  static const _kFontFam = 'MyPortfolio';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_mail = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xf0c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_in = IconData(0xf0e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack_overflow = IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xf17b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab = IconData(0xf296, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_store = IconData(0xf36f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_store_ios = IconData(0xf370, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_m = IconData(0xf3c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_open = IconData(0xf49e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
